### ISSUE TITLE
Support neovim

### ISSUE THREAD

**Issue by tamago324** [tamago324/vim-browsersync#4]
see https://github.com/pianocomposer321/vim-browsersync

**Comment by pianocomposer321** [comment]
I have completed the fork and submitted a pull request. This should be working.

I believe this issue can be closed. :-)

BTW, thanks for making this plugin. I'm just getting into front-end web development, and this plugin makes it so much easier! And thanks to the small and neat code-base, it was trivial to add support for neovim so I could use it.

**Comment by tamago324** [comment]
Thank you for the pull request!

Also, I have used it when I was learning about the front end of the web. Glad I could help!
