### ISSUE TITLE
It is not watching for CSS

### ISSUE THREAD

**Issue by adriano-pinaffo** [tamago324/vim-browsersync#6]
How to make it refresh on CSS updates?

**Comment by pianocomposer321** [comment]
Hmm...works for me.

What is the file structure of your project? That may have something to do with it.

**Comment by tamago324** [comment]
@adriano-pinaffo
Is there a way to reproduce this?
Does it happen in https://github.com/tamago324/vim-browsersync/blob/master/example/style.css? Or is it a more complex project?

**Comment by adriano-pinaffo** [comment]
That is so weird. I closed and re-opened the files and now they work just fine. Sorry for opening this ticket

**Comment by tamago324** [comment]
@adriano-pinaffo 
No, I'm glad it works.
If you have any further questions, please open an issue.
